### ISSUE TITLE
Upload 0.2.1 to Hackage

### ISSUE THREAD

**Issue by joachifm** [vimus/vimus#76]
It'd be nice to have a GHC 7.10 compatible on Hackage. I just realised that I cannot upload new versions, however. @sol, will you please upload the new version?

**Comment by sol** [comment]
Joachim, I added you to the maintainers group on Hackage.  You can upload the new version, if you want to.  Otherwise I can do it later.

**Comment by joachifm** [comment]
Cool. 0.2.1 is now on Hackage.

**Comment by sol** [comment]
Thx :)
