### ISSUE TITLE
Use mpd from different port?

### ISSUE THREAD

**Issue by sid-kap** [vimus/vimus#79]
Can I change the port that vimus tries to connect to? I looked in the README, but I couldn't find this documented.

**Comment by sid-kap** [comment]
I realized that libmpd detects this by checking the environment variable `MPD_PORT`.

1) Should we make a way to specify this in the vimus config file? Environment variables are messy.
2) Should we put this in the documentation?

I would be willing to send a PR if this seems like a good idea to you.

**Comment by sol** [comment]
@sid-kap You can also specify it through `-p` or `--port` on the command-line.

Regarding extending the configuration file, currently the configuration file is evaluated at run time and it may turn out to be somewhat messy to change the port at runtime.  But you may give it a try and see how it goes.

Alternatively something an alias, e.g. for bash, like

```
alias vimus='vimus -p 1234'
```

may be a solution.

Regarding documentation, we may mention in the `README` that you can set host and port on the command line and that you should look at the output of `--help` for more information (patches welcome).

**Comment by joachifm** [comment]
Mentioning `MPD_HOST` and `MPD_PORT` in the README makes sense to me.

**Comment by sid-kap** [comment]
Sure, I can send a PR editing the README.
