### ISSUE TITLE
Binding to delete an album from the playlist

### ISSUE THREAD

**Issue by TedTed** [vimus/vimus#82]
Hi — and first, thanks for the awesome music reader :-)

In the same way "A" adds an album to the playlist; it'd be great if "D" would remove an album from the playlist. I can't find a way to do that without a specific binding, so I have to press "d" many times (or selecting things with "v" clumsily) if I change my mind about what I'm listening to.

I'm using vimus 0.2.1 on Debian Sid.

Cheers!

**Comment by haasn** [comment]
Quick idea on how to implement this fairly elegantly and without much hassle:

1. Add a command like "select-album" (`V` binding) to select the current album from song list widget. (Implementation note: perhaps make the underlying list widget implementation accept an "equality function", as with `group`)

2. Define `D` as literally just `:select-album<CR>:remove<CR>` (or perhaps define `:remove-album` as this operation)
